### ISSUE TITLE
opt_type_constraint_case getting stuck

### ISSUE THREAD

**Issue by jrmbchtl** [thewhiteninja/deobshell#2] opened 2022-01-10 11:31 UTC
the function opt_type_constraint_case(ast) is getting stuck at "Fix typename case from 'string' to 'String'"
It looks like the Element isn't getting replaced properly

**Comment by thewhiteninja** [comment] 2022-03-02 15:54
Do you have a sample?

**Comment by joeavanzato** [comment] 2023-02-17 16:54
Here is a sample - I am having the same issue.
- Raw PS1
[ADOperatingSystems.txt](https://github.com/thewhiteninja/deobshell/files/10769908/ADOperatingSystems.txt)

- Raw AST
[ADOperatingSystems.ps1.txt](https://github.com/thewhiteninja/deobshell/files/10769052/ADOperatingSystems.ps1.txt)

I have taken your code and basically merged certain sections with my own - I am first converting .ps1 into raw AST, then calling optimizer in same way as yourself - I am getting infinite messages like below;

'[02-17-2023 11:52:51] [DEBUG] Fix typename case from 'string' to 'String''

This happens on a few files and I'm not sure why but it is getting stuck in a loop - I am trying to debug as well.

**Comment by thewhiteninja** [comment] 2023-02-17 20:35
There was a problem with `opt_type_constraint_case` which change `string` to `String` and `opt_type_constraint_from_convert` which replace the type of `TypeConstraintAst` nodes with the static type of `ConvertExpressionAst`, in this case `String` to `string`.

fixed with 67e713c847b8cf79e54ede91227f3817bdefe32e

**Comment by joeavanzato** [comment] 2023-02-17 21:09
You are a boss - really, fixing a bug within 4 hours of having a sample is amazing (especially since this was opened a year ago lol), props to you!

I am using your tool in a combined ML workflow to analyze suspicious PowerShell files with both text classification and DNN learning - thank you very much for such an interesting approach to AST simplification/analysis.

(I confirmed that your patch mitigates the issue I was experiencing and this bug can probably be closed)

**Closed as completed** 2023-02-17 21:28 UTC
Labels: bug
